<?php $this->layout('layout/default', ['pageTitle' => 'Transactions']) ?>

<!-- <div class="flex p-1">
  <div class="overflow-x-auto">
    <table class="table table-xs">
      <thead>
        <tr>
          <th>id</th>
          <th>transaction_date</th>
          <th>type</th>
          <th>sort_code</th>
          <th>account_number</th>
          <th>description</th>
          <th>debit_amount</th>
          <th>credit_amount</th>
          <th>balance</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($transactions as $transaction): ?>
        <tr>
          <td><?= $this->e($transaction['id'])?></td>
          <td><?= $this->e($transaction['transaction_date'])?></td>
          <td><?= $this->e($transaction['type'])?></td>
          <td><?= $this->e($transaction['sort_code'])?></td>
          <td><?= $this->e($transaction['account_number'])?></td>
          <td><?= $this->e($transaction['description'])?></td>
          <td><?= $this->e($transaction['debit_amount'])?></td>
          <td><?= $this->e($transaction['credit_amount'])?></td>
          <td><?= $this->e($transaction['balance'])?></td>
        </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <th>id</th>
          <th>transaction_date</th>
          <th>type</th>
          <th>sort_code</th>
          <th>account_number</th>
          <th>description</th>
          <th>debit_amount</th>
          <th>credit_amount</th>
          <th>balance</th>
        </tr>
      </tfoot>
    </table>
  </div>
</div> -->

<div class="flex flex-col gap-2 p-3">
  <?php foreach ($transactions as $transaction): ?>
    <div class="rounded-2xl px-4 py-2 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 shadow-md hover:bg-[oklch(25%_0.015_254.09)] transition-colors duration-150">
      <div class="hidden sm:flex sm:flex-col sm:items-start w-1/5">
        <?php if ($transaction['debit_amount'] > 0): ?>
          <span class="badge badge-outline badge-error font-bold text-xs mt-1"><?=$transaction['type']?></span>
        <?php else: ?>
          <span class="badge badge-outline badge-success font-bold text-xs mt-1"><?=$transaction['type']?></span>
        <?php endif; ?>
      </div>

      <div class="flex flex-col gap-1 w-full sm:w-2/5">
        <div class="font-semibold truncate"><?=$transaction['description']?></div>
        <!-- <div class="text-xs text-[oklch(60%_0.05_149.579)] flex flex-wrap gap-2">ID: <?=$transaction['id']?></div> -->
      </div>

      <div class="flex flex-col items-end text-right w-full sm:w-1/3">
        <?php if ($transaction['debit_amount'] > 0): ?>
          <div class="text-xl text-error font-black font-mono">£<?=$transaction['debit_amount']?></div>
        <?php else: ?>
          <div class="text-xl text-success font-black font-mono">£<?=$transaction['credit_amount']?></div>
        <?php endif; ?>
      </div>
    </div>
  <?php endforeach; ?>
</div>